protected/models/DBDocument.php
<?php

/**
 * This is the model class for table "{{document}}".
 *
 * The followings are the available columns in table '{{document}}':
 * @property string $id
 * @property integer $post_id
 * @property string $file_name
 * @property string $type
 * @property integer $size
 * @property string $mime_type
 *
 * The followings are the available model relations:
 * @property Post $post
 */
class DBDocument extends CActiveRecord
{

    /**
     * Returns the static model of the specified AR class.
     * @param string $className active record class name.
     * @return DBDocument the static model class
     */
    public static function model($className = __CLASS__)
    {
        return parent::model($className);
    }

    /**
     * @return string the associated database table name
     */
    public function tableName()
    {
        return '{{document}}';
    }

    /**
     * @return array validation rules for model attributes.
     */
    public function rules()
    {
        // NOTE: you should only define rules for those attributes that
        // will receive user inputs.
        return array(
            array('file_name, type', 'required'),
            array('post_id, size', 'numerical', 'integerOnly' => true),
            array('id', 'length', 'max' => 17),
            array('type', 'length', 'max' => 4),
            array('mime_type', 'safe'),
            // The following rule is used by search().
            // Please remove those attributes that should not be searched.
            array('id, post_id, file_name, type, size, mime_type', 'safe', 'on' => 'search'),
            array('id, post_id, file_name, type, size, mime_type', 'safe', 'on' => 'sync'),
        );
    }

    public static function getPath()
    {
        return Yii::getPathOfAlias('webroot') . Yii::app()->params['docPath'];
    }

    public function getFilePath()
    {
        return self::getPath() . $this->id;
    }


    protected function beforeDelete()
    {
        parent::beforeDelete();
        if (@unlink($this->getFilePath())) {
            return TRUE;
        } else {
//          todo: error handling
            return TRUE;
        }
    }

    public function getUrl()
    {
        return Yii::app()->createUrl('/doc/download', array('id' => $this->id, 'filename' => $this->file_name));
    }

    public function getPreviewUrl()
    {
        if (in_array($this->type, array('pdf', 'png', 'txt', 'zip', 'avi'))) {
            $type = $this->type;
        } elseif (in_array($this->type, array('jpg', 'jpeg', 'JPG'))) {
            $type = 'jpg';
        } elseif (in_array($this->type, array('ppt', 'pptx'))) {
            $type = 'ppt';
        } elseif (in_array($this->type, array('xls', 'xlsx'))) {
            $type = 'xls';
        } elseif (in_array($this->type, array('doc', 'docx'))) {
            $type = 'doc';
        } else {
            $type = 'file';
        }
        return '/css/img/doc/' . $type . '.png';
    }

    /**
     * @return array relational rules.
     */
    public function relations()
    {
        // NOTE: you may need to adjust the relation name and the related
        // class name for the relations automatically generated below.
        return array(
            'post' => array(self::BELONGS_TO, 'Post', 'post_id'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels()
    {
        return array(
            'id' => 'ID',
            'post_id' => 'Post',
            'file_name' => 'File Name',
            'type' => 'Type',
            'size' => 'Size',
            'mime_type' => 'Mime Type',
        );
    }

    /**
     * Retrieves a list of models based on the current search/filter conditions.
     * @return CActiveDataProvider the data provider that can return the models based on the search/filter conditions.
     */
    public function search()
    {
        // Warning: Please modify the following code to remove attributes that
        // should not be searched.

        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id, true);
        $criteria->compare('post_id', $this->post_id);
        $criteria->compare('file_name', $this->file_name, true);
        $criteria->compare('type', $this->type, true);
        $criteria->compare('size', $this->size);
        $criteria->compare('mime_type', $this->mime_type, true);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function searchDocs()
    {
        // Warning: Please modify the following code to remove attributes that
        // should not be searched.

        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id, true);
        $criteria->compare('post_id', $this->post_id);
        $criteria->compare('file_name', $this->file_name, true);
        $criteria->compare('type', $this->type, true);
        $criteria->compare('size', $this->size);
        $criteria->compare('mime_type', $this->mime_type, true);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

}

protected/models/Post.php
<?php

class Post extends CActiveRecord
{

    /**
     * The followings are the available columns in table 'tbl_post':
     * @property integer $id
     * @property string $title
     * @property string $preview_text
     * @property string $content
     * @property string $tags
     * @property integer $status
     * @property integer $create_time
     * @property integer $update_time
     * @property integer $author_id
     * @property boolean $on_main
     * @property boolean $is_doc
     *
     * @property boolean $view_count_local
     * @property boolean $view_count_web
     *
     *
     *
     * @property string $related_posts
     *
     * @property boolean $is_event
     * @property string $event_from
     * @property string $event_to
     * @property string $event_note
     *
     * The followings are the available model relations:
     * @property Comment[] $comments
     * @property PostCategory[] $postCategories
     * @property BDImage[] $postImages
     * @property DBDocument[] $postDocuments
     */
    const STATUS_DRAFT = 1;
    const STATUS_PUBLISHED = 2;
    const STATUS_ARCHIVED = 3;
    const STATUS_IMPORTANT = 4;
    const STATUS_HIDDEN = 5;


    public $documents;
    public $videoHref;
    public $videoLocal;
    protected $_oldTags;

//    public $categories;

    /**
     * Returns the static model of the specified AR class.
     * @return CActiveRecord the static model class
     */
    public static function model($className = __CLASS__)
    {
        return parent::model($className);
    }

    /**
     * @return string the associated database table name
     */
    public function tableName()
    {
        return '{{post}}';
    }

    public function behaviors()
    {
        return array(
            'EJsonBehavior' => array(
                'class' => 'ext.behaviors.EJsonBehavior'
            ),
        );
    }

    /**
     * @return array validation rules for model attributes.
     */
    public function rules()
    {
        // NOTE: you should only define rules for those attributes that
        // will receive user inputs.
        return array(
            array('title, preview_text, status', 'required', 'on' => 'insert, update'),
            array('title, categories', 'required', 'on' => 'doc'),
            array('status', 'in', 'range' => array(1, 2, 3, 4)),
            array('content, related_posts', 'safe'),
            array('event_from', 'validateEvent', 'on' => 'insert, update'),
            array('is_event, event_from, event_to, event_note', 'safe'),
            array('content, related_posts, preview_text', 'default', 'value' => ''),
            array('is_doc', 'default', 'value' => 1, 'on' => 'doc'),
            array('preview_text', 'safe', 'on' => 'doc'),
            array('title', 'length', 'max' => 128),
            array('tags', 'match', 'pattern' => '/^[\D\w\s,]+$/ui', 'message' => 'Тэги могут содержать только буквы.'),
            array('tags', 'normalizeTags'),
            array('update_time, videoHref, videoLocal, on_main, categories, documents', 'safe'),
            array('title, status, categories, images', 'safe', 'on' => 'search'),
            array('preview_text', 'safe', 'on' => 'doc'),
            array('id, title, preview_text, status, content, tags, status, create_time, update_time, author_id, on_main, view_count_local, view_count_web, is_doc', 'safe', 'on' => 'sync, safe'),
        );
    }

    public function validateEvent($attribute) {
        if ($this->is_event && empty($this->$attribute)) {
            $this->addError($attribute, "Если привязано событие, необходимо заполнить поле " . $this->getAttributeLabel($attribute));
        }
    }

    /**
     * @return array relational rules.
     */
    public function relations()
    {
        // NOTE: you may need to adjust the relation name and the related
        // class name for the relations automatically generated below.
        return array(
            'author' => array(self::BELONGS_TO, 'User', 'author_id'),
            'comments' => array(self::HAS_MANY, 'Comment', 'post_id', 'condition' => 'comments.status=' . Comment::STATUS_APPROVED, 'order' => 'comments.create_time DESC'),
            'commentCount' => array(self::STAT, 'Comment', 'post_id', 'condition' => 'status=' . Comment::STATUS_APPROVED),
            'postImages' => array(self::HAS_MANY, 'BDImage', 'post_id'),
            'postDocuments' => array(self::HAS_MANY, 'DBDocument', 'post_id', 'order' => 'file_name ASC'),
            'postVideos' => array(self::HAS_MANY, 'Video', 'post_id'),
            'postCategories' => array(self::HAS_MANY, 'PostCategory', 'post_id'),
            'categories' => array(self::HAS_MANY, 'Category', array('category_id' => 'id'), 'through' => 'postCategories'),
            'docCategories' => array(self::HAS_MANY, 'Category', array('category_id' => 'id'), 'through' => 'postCategories'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels()
    {
        return array(
            'id' => 'Id',
            'title' => 'Заголовок',
            'preview_text' => 'Анонс',
            'content' => 'Содержание',
            'tags' => 'Тэги',
            'status' => 'Статус',
            'create_time' => 'Время создания',
            'update_time' => 'Время обновления',
            'author_id' => 'Автор',
            'documents' => 'Документы',
            'documents[]' => 'Документы',
            'images' => 'Изображения',
            'videoHref' => 'Видео на YouTube',
            'videoLocal' => 'Видео в интранет',
            'on_main' => 'Разместить на главной',
            'view_count_local' => 'Просмотров в локальной сети',
            'view_count_web' => 'Просмотров в интернете',
            'related_posts' => 'Связанные записи',
            'is_event' => 'Привязать событие',
            'event_from' => 'Начало события',
            'event_to' => 'Окончание события',
            'event_note' => 'Заметка',
            //  'postCategories.categories' => 'Категории',
        );
    }

    public function updateViewCount()
    {
        $isWeb = Yii::app()->params['isWeb'];
        if ($isWeb) {
            $this->updateCounters(array('view_count_web' => 1), 'id = :id', array(':id' => $this->id));
        } else {
            $this->updateCounters(array('view_count_local' => 1), 'id = :id', array(':id' => $this->id));
        }
    }

    public function getViewCount()
    {
        $isWeb = Yii::app()->params['isWeb'];
        if ($isWeb) {
            return $this->view_count_web;
        } else {
            if ($this->view_count_local == 0 && $this->view_count_web != 0) {
                return  floor($this->view_count_web / 4);
            } else {
                return $this->view_count_local;
            }
        }
    }

    public function getBreadcrumbs()
    {
        $crumbs = array();
        $subRootLabel = $this->is_doc ? 'Документы' : 'Новости';

        $crumbs[$subRootLabel] = array($this->controllerName . '/index');

        $cats = array();
        foreach ($this->getCategoriesList() as $id => $cat) {
            $cats[] = CHtml::link($cat, array($this->controllerName . '/index', 'cat' => $id), array('style' => 'font-weight: normal;'));
        }
        $crumbs[] = implode(', ', $cats);
        $crumbs[] = $this->title;
        return $crumbs;
    }

    public function getCategoriesList()
    {

        $list = array();
        if (isset($this->categories)) {
            $list = CHtml::listData($this->categories, 'id', 'label');
        }
        return $list;
    }

    public function getDocCategoriesList()
    {

        $list = array();
        if (isset($this->categories)) {
            $list = CHtml::listData($this->categories, 'id', 'label');
        }
        return $list;
    }


    public function getImagesLinks()
    {
        $images = array();
        if (!empty($this->postImages)) {
            foreach ($this->postImages as $image) {
                $images[] = array(
                    'biggest' => Yii::app()->request->baseUrl . '/files/images/' . $image->file_name,
                    'smallest' => Yii::app()->request->baseUrl . '/files/images/thumbs/150x150/' . $image->file_name,
                );
            }
        }
        return $images;
    }

    public function getControllerName()
    {
        return $this->is_doc ? 'doc' : 'post';
    }

    /**
     * @return string the URL that shows the detail of the post
     */
    public function getUrl()
    {
        return Yii::app()->createUrl($this->controllerName . '/view', array(
            'id' => $this->id,
            'title' => $this->title,
        ));
    }

    /**
     * @return array a list of links that point to the post list filtered by every tag of this post
     */
    public function getTagLinks()
    {
        $links = array();
        foreach (Tag::string2array($this->tags) as $tag)
            $links[] = CHtml::link(CHtml::encode($tag), array('post/index', 'tag' => $tag));
        return $links;
    }

    /**
     * Normalizes the user-entered tags.
     */
    public function normalizeTags($attribute, $params)
    {
        $this->tags = Tag::array2string(array_unique(Tag::string2array($this->tags)));
    }

    /**
     * Adds a new comment to this post.
     * This method will set status and post_id of the comment accordingly.
     * @param Comment the comment to be added
     * @return boolean whether the comment is saved successfully
     */
    public function addComment($comment)
    {
        if (Yii::app()->params['commentNeedApproval'])
            $comment->status = Comment::STATUS_PENDING;
        else
            $comment->status = Comment::STATUS_APPROVED;
        $comment->post_id = $this->id;
        return $comment->save();
    }

    /**
     * This is invoked when a record is populated with data from a find() call.
     */
    protected function afterFind()
    {

protected/views/post/_preview.php
<?php ?>
<div class="post">
    <div class="title">
        <?php echo CHtml::link(CHtml::encode($data->title), $data->url); ?>
        <?php echo CHtml::link($data->viewCount, '', array('id' => 'counter', 'title' => "Просмотры - {$data->viewCount}")) ?>
    </div>
    <div class="author">
        размещено <?php echo Yii::app()->dateFormatter->format('d MMMM yyyy', $data->update_time); ?>
    </div>
    <div class="content">
        <?php
        $this->beginWidget('CMarkdown', array('purifyOutput' => false));
        echo $data->preview_text;
        $this->endWidget();
        ?>
    </div>
    <div class="nav">
        <?php if (!empty($data->tagLinks)) : ?>
            <b>Тэги:</b>
            <?php echo implode(', ', $data->tagLinks); ?>
            <br/>
        <?php endif; ?>

        <?php
        $this->widget('zii.widgets.jui.CJuiButton', array(
            'name' => 'button' . $data->id,
            'caption' => 'Подробнее',
            'url' => $data->url,
            'buttonType' => 'link',
            'htmlOptions' => array('class' => 'btn-more',),
            'options' => array(
                'icons' => array(
//                        'primary' => 'ui-icon-arrow-1-e',
                    'secondary' => 'ui-icon-arrow-1-e',
                ),
            ),
        ));
        ?> | Обновлён <?php echo date('F j, Y', $data->update_time); ?>
    </div>
</div>

protected/views/post/_preview_minimal.php
<div class="post">
    <div class="title" >
        <?php echo CHtml::link(CHtml::encode($data->title), $data->url); ?>
        <?php echo CHtml::link($data->viewCount, '', array('id' => 'counter', 'title' => "Просмотры - {$data->viewCount}")) ?>
    </div>
    <div class="content">
        <?php if (!empty($data->postVideos) && !empty($data->postVideos[0]->href) && !empty($data->postVideos[0]->local)): ?>
            <div class="post__video_preview">
                <?php
                $this->widget('VideoWidget', array(
                    'videoModel' => $data->postVideos[0]
                ));
                ?>
            </div> 
        <?php endif; ?>

        <?php
        $this->beginWidget('CMarkdown', array('purifyOutput' => false));

        echo $data->preview_text;

        echo ' ' . CHtml::link('<i>читать далее</i>', $data->url);
        $this->endWidget();
        ?>

    </div>
    <!--    <div >
    <?php if (!empty($data->tagLinks)) : ?>
                                        <b>Тэги:</b>
        <?php echo implode(', ', $data->tagLinks); ?>
                                        <br/>
    <?php endif; ?>
        </div>-->
</div>

protected/views/post/_uploadform.php
<!-- The file upload form used as target for the file upload widget -->
<?php if ($this->showForm) echo CHtml::beginForm($this->url, 'post', $this->htmlOptions); ?>
<!-- The fileupload-buttonbar contains buttons to add/delete files and start/cancel the upload -->
<div class="row fileupload-buttonbar">
    <div class="col-lg-7">
        <!-- The fileinput-button span is used to style the file input field as button -->
        <span class="btn btn-success fileinput-button">
            <i class="glyphicon glyphicon-plus"></i>
            <span>Добавить файлы...</span>
            <?php
            if ($this->hasModel()) :
                echo BsHtml::activeFileField($this->model, $this->attribute, $htmlOptions) . "\n";
            else :
                echo BsHtml::fileField($name, $this->value, $htmlOptions) . "\n";
            endif;
            ?>
        </span>
        <!-- The global file processing state -->
        <span class="fileupload-process"></span>
    </div>
    <!-- The global progress state -->
    <div class="col-lg-5 fileupload-progress fade">
        <!-- The global progress bar -->
        <div class="progress progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100">
            <div class="progress-bar progress-bar-success" style="width:0%;"></div>
        </div>
        <!-- The extended global progress state -->
        <div class="progress-extended">&nbsp;</div>
    </div>
</div>
<!-- The table listing the files available for upload/download -->
<table role="presentation" class="table table-striped"><tbody class="files"></tbody></table>
    <?php if ($this->showForm) echo CHtml::endForm(); ?>


<script>

//    $(function () {
//        'use strict';
//
//        // Initialize the jQuery File Upload widget:
//        $('#fileupload').fileupload({
//            // Uncomment the following to send cross-domain cookies:
//            //xhrFields: {withCredentials: true},
//            url: 'server/php/'
//        });
//
//        // Enable iframe cross-domain access via redirect option:
//        $('#fileupload').fileupload(
//                'option',
//                'redirect',
//                window.location.href.replace(
//                        /\/[^\/]*$/,
//                        '/cors/result.html?%s'
//                        )
//                );
//
//        if (window.location.hostname === 'blueimp.github.io') {
//            // Demo settings:
//            $('#fileupload').fileupload('option', {
//                url: '//jquery-file-upload.appspot.com/',
//                // Enable image resizing, except for Android and Opera,
//                // which actually support image resizing, but fail to
//                // send Blob objects via XHR requests:
//                disableImageResize: /Android(?!.*Chrome)|Opera/
//                        .test(window.navigator.userAgent),
//                maxFileSize: 999000,
//                acceptFileTypes: /(\.|\/)(gif|jpe?g|png)$/i
//            });
//            // Upload server status check for browsers with CORS support:
//            if ($.support.cors) {
//                $.ajax({
//                    url: '//jquery-file-upload.appspot.com/',
//                    type: 'HEAD'
//                }).fail(function () {
//                    $('<div class="alert alert-danger"/>')
//                            .text('Upload server currently unavailable - ' +
//                                    new Date())
//                            .appendTo('#fileupload');
//                });
//            }
//        } else {
//            // Load existing files:
//            $('#fileupload').addClass('fileupload-processing');
//            $.ajax({
//                // Uncomment the following to send cross-domain cookies:
//                //xhrFields: {withCredentials: true},
//                url: $('#fileupload').fileupload('option', 'url'),
//                dataType: 'json',
//                context: $('#fileupload')[0]
//            }).always(function () {
//                $(this).removeClass('fileupload-processing');
//            }).done(function (result) {
//                $(this).fileupload('option', 'done')
//                        .call(this, $.Event('done'), {result: result});
//            });
//        }
//
//    });
</script>

protected/views/post/_view.php
<div class="post">
    <div class="post__title">
        <?php echo CHtml::link(CHtml::encode($data->title), $data->url, array('class' => 'post__link')); ?>

        <?php if (!Yii::app()->user->isGuest) : ?>
            <?php
            $this->widget('zii.widgets.jui.CJuiButton', array(
                'name' => 'button' . $data->id,
                'caption' => 'Изменить',
                'options' => array(
                    'icons' => array(
                        'primary' => 'ui-icon-pencil',
                    ),
                ),
                'url' => array('update', 'id' => $data->id),
                'buttonType' => 'link',
                'htmlOptions' => array('class' => 'post__btn_action_edit'),
            ));
            ?>
        <?php endif; ?>
    </div>


    <div class="post__author">
        размещено <?php echo Yii::app()->dateFormatter->format('d MMMM yyyy', $data->update_time); ?>
    </div>

    <div class="content">
        <strong>
            <?php
            $this->beginWidget('CMarkdown', array('purifyOutput' => false));
            echo $data->preview_text;
            $this->endWidget();
            ?>
        </strong>
        <?php
        $this->beginWidget('CMarkdown', array('purifyOutput' => true));
        echo $data->content;
        $this->endWidget();
        ?>

        <?php if (!empty($data->postVideos) && !empty($data->postVideos[0]->href) && !empty($data->postVideos[0]->local)): ?>
            <div class="post__video_detail">
                <?php
                $this->widget('VideoWidget', array(
                    'videoModel' => $data->postVideos[0]
                ));
                ?>
            </div>
        <?php endif; ?>

        <?php if (!empty($data->postDocuments)): ?>
            <h2 class="heading heading_type_attach" id="files"><i class="fa fa-files-o" aria-hidden="true"></i> Приложенные
                документы </h2>
            <div class="list_type_doc">
                <? foreach ($data->postDocuments as $doc): ?>
                    <a class="list__item" target="_blank"
                       href="<?= $doc->getUrl() ?>">
                        <div class="list__preview" style="background-image: url('<?= $doc->previewUrl ?>');"></div>
                        <div class="list__label">
                            <?= $doc->file_name ?>
                        </div>
                        <div class="list__action">
                            <i class="fa fa-download" aria-hidden="true"></i>
                        </div>
                    </a>
                <? endforeach; ?>
            </div>
        <?php endif; ?>
    </div>

    <?php if ($related = $data->relatedPosts): ?>
        <div class="post__related">
            <h2 class="heading heading_type_related"><i class="fa fa-link" aria-hidden="true"></i> Связанные записи
            </h2>
            <div class="list_type_related">
                <? foreach ($related as $post): ?>
                    <a class="list__item"
                       href="<?= $post->getUrl() ?>">
                        <div class="list__preview">
                            <? if ($post->is_doc): ?>
                                <i class="fa  fa-file-archive-o" aria-hidden="true"></i>
                            <? else: ?>
                                <i class="fa  fa-file-text-o" aria-hidden="true"></i>
                            <? endif; ?>

                        </div>
                        <div class="list__label">
                            <div class="list__heading">
                                <?= $post->title ?>
                            </div>
                            <div class="list__subheading">
                                <? if ($post->is_doc): ?>
                                    Документы >
                                <? else: ?>
                                    Анонсы и новости >
                                <? endif; ?>
                                <? foreach ($post->getCategoriesList() as $cat): ?>
                                    <?= $cat ?>
                                <? endforeach; ?>

                            </div>
                        </div>

                    </a>
                <? endforeach; ?>
            </div>
        </div>
    <?php endif; ?>


    <div class="nav">
        <b>Тэги:</b>
        <?php echo implode(', ', $data->tagLinks); ?>
        <br/>

        <?php echo "Просмотры -  {$data->viewCount}"; ?> |
        Последний раз обновлено <?php echo Yii::app()->dateFormatter->format('d MMMM yyyy', $data->update_time); ?>
        <span style="text-align: right">
            <?php
            $this->widget('ext.mPrint.mPrint', array(
                'title' => $data->title,
                'element' => '.post',
                'exceptions' => array(
                    '.nav',
                    '.title',
                ),
                'publishCss' => true,
            ));
            ?>
        </span>
    </div>
</div>

protected/views/post/admin.php
<?php
$this->pageTitle = 'Управление записями';
$this->breadcrumbs = array(
    'Управление записями',
);
?>
<div class="row">
    <div class="col-xs-12">
        <?php
        $this->widget('ext.groupgridview.BootGroupGridView', array(
            'id' => 'post-grid',
            'dataProvider' => $model->search(),
            'columns' => array(
                array(
                    'name' => 'title',
                    'type' => 'raw',
                    'value' => 'CHtml::link(CHtml::encode($data->title), $data->url)'
                ),
                array(
                    'name' => 'status',
                    'value' => 'Lookup::item("PostStatus",$data->status)',
                    'filter' => Lookup::items('PostStatus'),
                ),
                array(
                    'name' => 'create_time',
                    'type' => 'datetime',
                    'filter' => false,
                ),
                array(
                    'name' => 'update_time',
                    'type' => 'datetime',
                    'filter' => false,
                ),
                array(
                    'class' => 'bootstrap.widgets.BsButtonColumn',
                ),
            ),
        ));
        ?>
    </div>
</div>

protected/views/post/cat.php
<?php  if (isset($catName)): ?>
<h1 ><i><?php echo CHtml::encode($catName);?></i></h1>
<?php endif; ?>
<?php if (!empty($_GET['tag'])): ?>
    <h1>Записи, отмеченные тэгом <i>"<?php echo CHtml::encode($_GET['tag']); ?>"</i></h1>
<?php endif; ?>

<?php
$this->widget('zii.widgets.CListView', array(
    'dataProvider' => $dataProvider,
    'itemView' => '_preview',
    'template' => "{items}\n{pager}",
    'emptyText' => 'Нет статей по этой категории'
));
?>

protected/views/post/create.php
<?php
$this->pageTitle = 'Новая запись';
$this->breadcrumbs = array(
    'Новая запись',
);
?>

<?php
echo $this->renderPartial('_form', array(
    'model' => $model,
    'images' => $images,
));
?>

protected/views/post/index.php
<?php if (isset($catName)): ?>
    <h1 class="heading heading_type_cat"><?php echo CHtml::encode($catName); ?></h1>
    <?php $this->pageTitle = $catName . ' - ' . Yii::app()->name;?>
<?php elseif (!empty($_GET['tag'])): ?>
    <h1 class="heading heading_type_tag">Записи, отмеченные тэгом <i>"<?php echo CHtml::encode($_GET['tag']); ?>"</i></h1>
    <?php $this->pageTitle = 'Тэг: ' . $_GET['tag'] . ' - ' . Yii::app()->name;?>
<?php else: ?>
    <h1 class="heading heading_type_cat">Анонсы и новости</h1>
    <?php $this->pageTitle = 'Новости - ' . Yii::app()->name;?>
<?php endif; ?>

<?php
$this->widget('ext.widgets.DListView.DListView', array(
    'dataProvider' => $dataProvider,
    'itemView' => '_preview',
    'template' => "{items}\n{pager}",
    'emptyText' => 'Нет статей по этой категории'
));
?>
<br>
<br>

protected/views/post/update.php
<?php
$this->pageTitle = array('Изменить', CHtml::encode($model->title));
$this->breadcrumbs = array(
    'Управление' => array('admin'),
    $model->title => $model->url,
    'Изменить',
);
?>

<?php
echo $this->renderPartial('_form', array(
    'model' => $model,
    'images' => $images,
));
?>

protected/views/post/view.php
<?php
//$this->breadcrumbs = array(
//    $model->title,
//);

header("Access-Control-Allow-Origin: *");
$this->breadcrumbs = $model->getBreadcrumbs();

$this->pageTitle = $model->title . ' - ' . Yii::app()->name;
?>

<?php
$this->renderPartial('_view', array(
    'data' => $model,
));
?>

<?php if (!empty($model->postImages)): ?>
    <div id="galery">
        <h1>Галерея</h1>
        <?php
        foreach ($model->getImagesLinks() as $image) {
            $this->widget('ext.lyiightbox.LyiightBox2', array(
                'thumbnail' => $image['smallest'],
                'image' => $image['biggest'],
                    //'title' => 'Sample Image 1.'
            ));
        }
        ?>
    </div>
<?php endif; ?>